#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

if $(git diff --name-only HEAD@{1} HEAD | grep package-lock.json) ; then
    echo "📦 package-lock.json changed. Running npm ci to update your dependencies..."
    npm ci
else
    echo "📦 no need to update dependencies"
fi
